name: Build LSQUIC with BoringSSL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows-static
          - os: macos-latest
            triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout LSQUIC repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Go (for BoringSSL build)
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install Build Tools (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y ninja-build
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install ninja
        fi
      shell: bash

    - name: Setup MSVC Developer Command Prompt (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-${{ matrix.triplet }}-vcpkg-cache-v2

    - name: Bootstrap vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          ./bootstrap-vcpkg.bat -disableMetrics
        else
          ./bootstrap-vcpkg.sh -disableMetrics
        fi
      shell: bash

    - name: Install Dependencies via vcpkg
      run: |
        ./vcpkg/vcpkg install zlib:${{ matrix.triplet }}
        ./vcpkg/vcpkg install libevent:${{ matrix.triplet }}
      shell: bash

    - name: Build BoringSSL from Source (Disable Tests)
      run: |
        git clone https://boringssl.googlesource.com/boringssl
        cd boringssl
        git checkout 9fc1c33e9c21439ce5f87855a6591a9324e569fd
        # FIX: Disable tests with -DBUILD_TESTING=OFF to prevent the gcc warning from failing the build.
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
        cmake --build build --config Release
      shell: bash

    - name: Configure and Build LSQUIC
      # FIX: Use bash shell for all OSes for command consistency.
      # FIX: Use single-line, explicit commands to avoid syntax errors.
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBORINGSSL_DIR=${{ github.workspace }}/boringssl -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
        cmake --build build --config Release
      shell: bash

    - name: Package Build Artifacts
      run: |
        $artifactDir = "lsquic-dist-${{ matrix.triplet }}"
        New-Item -ItemType Directory -Path "$artifactDir/lib" -Force
        New-Item -ItemType Directory -Path "$artifactDir/include" -Force

        Copy-Item -Path "include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "build/lib/*" -Destination "$artifactDir/lib/" -ErrorAction SilentlyContinue
        Copy-Item -Path "build/bin/*" -Destination "$artifactDir/lib/" -ErrorAction SilentlyContinue # For Windows DLLs
        Copy-Item -Path "boringssl/build/crypto/*" -Destination "$artifactDir/lib/" -ErrorAction SilentlyContinue
        Copy-Item -Path "boringssl/build/ssl/*" -Destination "$artifactDir/lib/" -ErrorAction SilentlyContinue
        Copy-Item -Path "boringssl/include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "vcpkg/installed/${{ matrix.triplet }}/lib/*" -Destination "$artifactDir/lib/" -ErrorAction SilentlyContinue
        Copy-Item -Path "vcpkg/installed/${{ matrix.triplet }}/include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue

        if ("${{ runner.os }}" -eq "Windows") {
          Compress-Archive -Path $artifactDir -DestinationPath "${artifactDir}.zip"
        } else {
          tar -czf "${artifactDir}.tar.gz" -C $artifactDir .
        }
      shell: pwsh

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lsquic-release-${{ runner.os }}-${{ matrix.triplet }}
        path: lsquic-dist-${{ matrix.triplet }}.${{ runner.os == 'Windows' && 'zip' || 'tar.gz' }}
        retention-days: 7