name: Build Remote LSQUIC with BoringSSL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows-static
          - os: macos-latest
            triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go (for BoringSSL build)
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install Build Tools and NASM
      if: runner.os != 'Windows'
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y git ninja-build nasm
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install git ninja nasm
        fi
      shell: bash

    - name: Install NASM (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/setup-nasm@v1

    - name: Setup MSVC Developer Command Prompt (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Clone Required Repositories
      run: |
        git clone https://github.com/litespeedtech/lsquic.git
        git clone https://boringssl.googlesource.com/boringssl
        git clone https://github.com/microsoft/vcpkg.git
      shell: bash

    - name: Bootstrap vcpkg
      working-directory: ${{ github.workspace }}/vcpkg
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          ./bootstrap-vcpkg.bat -disableMetrics
        else
          ./bootstrap-vcpkg.sh -disableMetrics
        fi
      shell: bash

    - name: Install Dependencies via vcpkg
      working-directory: ${{ github.workspace }}/vcpkg
      run: ./vcpkg install zlib:${{ matrix.triplet }} libevent:${{ matrix.triplet }}
      shell: bash

    - name: Build BoringSSL from Source
      working-directory: ${{ github.workspace }}/boringssl
      run: |
        git checkout 9fc1c33e9c21439ce5f87855a6591a9324e569fd
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sed -i 's/-Werror//g' CMakeLists.txt
        fi
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
      shell: bash

    - name: Configure and Build LSQUIC (Linux/macOS)
      if: runner.os != 'Windows'
      working-directory: ${{ github.workspace }}/lsquic
      run: |
        git submodule update --init --recursive
        # FIX: Explicitly provide the full paths to the BoringSSL libraries and includes
        cmake -S . -B build -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DBORINGSSL_INCLUDE_DIR=${{ github.workspace }}/boringssl/include `
          -DBORINGSSL_LIB_crypto=${{ github.workspace }}/boringssl/build/crypto/libcrypto.a `
          -DBORINGSSL_LIB_ssl=${{ github.workspace }}/boringssl/build/ssl/libssl.a `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
        cmake --build build --config Release
      shell: bash

    - name: Configure and Build LSQUIC (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{ github.workspace }}/lsquic
      # FIX: Use PowerShell on Windows to correctly handle paths and the MSVC environment
      shell: pwsh
      run: |
        git submodule update --init --recursive
        # FIX: Explicitly provide the full paths to the BoringSSL libraries and includes
        cmake -S . -B build -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DBORINGSSL_INCLUDE_DIR=${{ github.workspace }}/boringssl/include `
          -DBORINGSSL_LIB_crypto=${{ github.workspace }}/boringssl/build/crypto/crypto.lib `
          -DBORINGSSL_LIB_ssl=${{ github.workspace }}/boringssl/build/ssl/ssl.lib `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
        cmake --build build --config Release

    - name: Package Build Artifacts
      shell: pwsh
      run: |
        $artifactDir = "lsquic-dist-${{ matrix.triplet }}"
        New-Item -ItemType Directory -Path "$artifactDir/lib" -Force
        New-Item -ItemType Directory -Path "$artifactDir/include" -Force

        Copy-Item -Path "${{ github.workspace }}/lsquic/build/lib/*" -Destination "$artifactDir/lib/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/lsquic/build/bin/*" -Destination "$artifactDir/lib/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/lsquic/include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/boringssl/build/crypto/*" -Destination "$artifactDir/lib/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/boringssl/build/ssl/*" -Destination "$artifactDir/lib/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/boringssl/include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/vcpkg/installed/${{ matrix.triplet }}/lib/*" -Destination "$artifactDir/lib/" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "${{ github.workspace }}/vcpkg/installed/${{ matrix.triplet }}/include/*" -Destination "$artifactDir/include/" -Recurse -ErrorAction SilentlyContinue

        if ("${{ runner.os }}" -eq "Windows") {
          Compress-Archive -Path $artifactDir -DestinationPath "${artifactDir}.zip"
        } else {
          tar -czf "${artifactDir}.tar.gz" -C $artifactDir .
        }

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lsquic-release-${{ runner.os }}-${{ matrix.triplet }}
        path: lsquic-dist-${{ matrix.triplet }}.${{ runner.os == 'Windows' && 'zip' || 'tar.gz' }}
        retention-days: 7