name: Build BoringSSL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # =============================================
  #  JOB: Build and Archive BoringSSL
  # =============================================
  build-boringssl:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Build Tools and NASM (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y git ninja-build nasm
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install git ninja nasm
          fi
        shell: bash

      - name: Install NASM (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build and Install BoringSSL
        run: |
          git clone https://boringssl.googlesource.com/boringssl.git
          cd boringssl
          # Using a known-good commit for stability
          git checkout 9fc1c33e9c21439ce5f87855a6591a9324e569fd
          # Remove -Werror on Linux to prevent build failures on newer compilers
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sed -i 's/-Werror//g' CMakeLists.txt
          fi
          # Configure, build, and install BoringSSL
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/boringssl-install
          cmake --build build --config Release
          cmake --install build
        shell: bash

      # This step uploads the final build results from the 'boringssl-install' directory
      - name: Upload BoringSSL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boringssl-build-${{ runner.os }}
          path: ${{ github.workspace }}/boringssl-install